name: Execute Commands on GCP Compute Engine Instance

on:
  push:
    branches:
      - staging

jobs:
  execute-commands-on-instance:
    runs-on: self-hosted

    steps:
    - name: Updating code on VM
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd application/userprofiling && \
          git pull origin staging && \
          composer install && \
          composer dumpautoload && \
          php artisan route:cache && \
          php artisan route:clear && \
          php artisan config:cache && \
          php artisan cache:clear && \
          php artisan config:clear